// Generated by Wrangler by running `wrangler types --x-include-runtime --env production`

interface Env {
	PREFIX_TO_IMAGES_KV: KVNamespace;
	IMAGES_KV: KVNamespace;
	ENVIRONMENT: "prod";
	ROOT_DOMAIN: "ting.dog";
	IMAGE_COORDINATOR: DurableObjectNamespace<import("./index").ImageCoordinator>;
	RATE_LIMITER: RateLimit;
	RATE_LIMITER_IMAGES: RateLimit;
	AI: Ai;
}
